from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import List
from rag_pipeline import RAGPipeline

# 1. Initialize FastAPI Application
app = FastAPI(
    title="AI Intern Week 5 - LLM & RAG",
    description="FastAPI backend exposing a Retrieval-Augmented Generation pipeline using ChromaDB and Gemini.",
    version="1.0.0"
)

# 2. Instantiate the RAG Pipeline globally
# This ensures it loads into memory only once when the server starts
try:
    pipeline = RAGPipeline(db_path="./chroma_db", collection_name="customer_faq")
except Exception as e:
    print(f"CRITICAL: Failed to initialize RAG Pipeline: {e}")
    pipeline = None


# 3. Define Pydantic Schemas for Input Data Validation
class QuestionRequest(BaseModel):
    question: str = Field(
        ...,
        description="The customer support question to ask the RAG system.",
        example="How can I track my order status?"
    )


# 4. Define Pydantic Schema for API Response Structure
class AnswerResponse(BaseModel):
    answer: str = Field(..., description="The factual answer generated by the LLM.")
    sources: List[str] = Field(..., description="The unique list of source documents used as context.")


# 5. Root Endpoint (Health Check / Smoke Test)
@app.get("/", tags=["General"])
async def root():
    return {
        "status": "online",
        "message": "Welcome to the Customer Support RAG API. Visit /docs for Swagger UI."
    }


# 6. Task Requirement Endpoint: POST /ask
@app.post("/ask", response_model=AnswerResponse, tags=["RAG Core"])
async def ask_question(payload: QuestionRequest):
    """
    Receives a customer question, retrieves relevant context from ChromaDB,
    and returns a deterministic response generated by Gemini along with its sources.
    """
    if pipeline is None:
        raise HTTPException(
            status_code=500,
            detail="RAG Pipeline service is currently unavailable. Check server logs."
        )

    try:
        # Run the query through your RAG pipeline
        result = pipeline.ask(payload.question)

        # FastAPI automatically packages this dict into the AnswerResponse model format
        return {
            "answer": result["answer"],
            "sources": result["sources"]
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"An error occurred while processing the RAG request: {str(e)}"
        )